%% Clear Command Window and Close Figures
close all;
clc;
% Create I/O Objects
% Sampling Freq (Hz)
Fs = 8000;

% Gen Noise
% Min/max peak of noise
 min = -1;
 max = 1;
 
 % 30 sec of noise
 sig = min + (max-min)*rand(30*Fs,1);
 T = length(sig);
 % Create Scopes
 TimeScope = dsp.TimeScope( ...  
 'SampleRate',Fs, ...    
 'TimeSpan',T/Fs, ...    
 'BufferLength',4*Fs, ...    
 'YLimits',[-1,1], ...    
 'TimeSpanOverrunAction','Scroll'); 
 SpectrumAnalyzer = dsp.SpectrumAnalyzer( ...    
 'SpectrumType','RMS', ...    
 'SampleRate',Fs, ...    
 'PlotAsTwoSidedSpectrum',false, ...    
 'YLimits',[-0.1 1.1], ...    
 'SpectralAverages',10, ...    
 'ShowLegend',true);
 % Filter
 n = 64;
 y = filter(sig,2500,Fs);
 % Display Time Scope
 TimeScope(y);
 % Display Spectral Analyzer
 SpectrumAnalyzer(y);