% Clear Workspace
clear;
close all;
clc;
% Gen Sweep
Fs = 8000;
frameSize = 20000;
chirp = dsp.Chirp('SampleRate',Fs,... 
    'SamplesPerFrame',frameSize,...
    'InitialFrequency',8000,...
    'Type', "Swept cosine",...
    'TargetFrequency',8000); 
% Create Scopes
SpectrumAnalyzer = dsp.SpectrumAnalyzer( ...
    'ViewType','Spectrogram', ... 
    'SampleRate',Fs, ...  
    'RBWSource','Property', ...  
    'RBW',500, ...   
    'TimeSpanSource','Property', ...  
    'TimeSpan',2, ...   
    'PlotAsTwoSidedSpectrum',false);

y = chirp()+ 0.05*randn(frameSize,1);
SpectrumAnalyzer(y);
